f-profile-basic-fix : basic.component.ts(278,7): error TS2739: Type 'String' is missing the following properties from type 'Districts': _id, _name, id, name